import Database from 'better-sqlite3';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const dbPath = path.resolve(__dirname, '../../../data/fb-agent.db');
const outputPath = path.resolve(__dirname, 'seed_brain.sql');

if (!fs.existsSync(dbPath)) {
  console.error(`Database not found at ${dbPath}`);
  process.exit(1);
}

const db = new Database(dbPath);

const tablesToExport = [
  'learning_journal',
  'codebase_map',
  'codebase_edges',
  'codebase_embeddings',
  'evolution_log'
];

let sqlOutput = `-- ============================================\n`;
sqlOutput += `-- AI Second Brain Seed Data (Autogenerated)\n`;
sqlOutput += `-- Exported on: ${new Date().toISOString()}\n`;
sqlOutput += `-- ============================================\n\n`;

// Disable foreign key checks for seeding
sqlOutput += `PRAGMA foreign_keys = OFF;\n\n`;

for (const table of tablesToExport) {
  console.log(`Exporting ${table}...`);
  try {
    const rows = db.prepare(`SELECT * FROM ${table}`).all();
    if (rows.length === 0) {
      console.log(`  Table ${table} is empty, skipping.`);
      continue;
    }

    sqlOutput += `-- Table: ${table} (${rows.length} rows)\n`;
    sqlOutput += `DELETE FROM ${table};\n`; // Clear existing if any

    for (const row of rows) {
      const keys = Object.keys(row as object);
      const values = keys.map(k => {
        const val = (row as any)[k];
        if (val === null) return 'NULL';
        if (typeof val === 'string') return `'${val.replace(/'/g, "''")}'`;
        if (Buffer.isBuffer(val)) return `X'${val.toString('hex')}'`;
        return val;
      });

      sqlOutput += `INSERT INTO ${table} (${keys.join(', ')}) VALUES (${values.join(', ')});\n`;
    }
    sqlOutput += `\n`;
    console.log(`  Exported ${rows.length} rows from ${table}`);
  } catch (err) {
    console.error(`  Failed to export ${table}:`, err);
  }
}

sqlOutput += `PRAGMA foreign_keys = ON;\n`;

fs.writeFileSync(outputPath, sqlOutput);
console.log(`\nSuccessfully generated ${outputPath} (${(sqlOutput.length / 1024).toFixed(2)} KB)`);

db.close();
